apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: ""
    server: https://561b5358-7b7a-4a6c-8fb2-22277c694679.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
users:
- name: do-nyc1-k8s-admin
  user:
    token: ""
